# Generated by Django 2.0.7 on 2018-08-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='标题')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(verbose_name='结束时间')),
                ('desc', models.TextField(verbose_name='投票简介')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('platform', models.IntegerField(choices=[(1, '微信'), (2, '网页')])),
                ('vote_time', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
            ],
        ),
        migrations.CreateModel(
            name='VotingCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField(default=0, verbose_name='投票数')),
            ],
            options={
                'verbose_name': '投票计数',
                'verbose_name_plural': '投票计数',
            },
        ),
        migrations.CreateModel(
            name='VotingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('avatar_url', models.URLField(verbose_name='头像链接')),
                ('desc', models.TextField(blank=True, default='', verbose_name='介绍')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('info_url', models.URLField(blank=True, null=True, verbose_name='详情链接')),
            ],
            options={
                'verbose_name': '投票对象',
                'verbose_name_plural': '投票对象',
            },
        ),
        migrations.AddField(
            model_name='votingcounter',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter', to='Vote.VotingItem', verbose_name='投票对象'),
        ),
        migrations.AddField(
            model_name='voter',
            name='counter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vote.VotingCounter', verbose_name='计数器'),
        ),
        migrations.AddField(
            model_name='voteevent',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vote.VotingItem', verbose_name='投票内容'),
        ),
    ]
