# Generated by Django 2.0.7 on 2018-08-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voteevent',
            options={'verbose_name': '投票项目', 'verbose_name_plural': '投票项目'},
        ),
        migrations.AlterModelOptions(
            name='voter',
            options={'verbose_name': '投票者', 'verbose_name_plural': '投票者'},
        ),
        migrations.RemoveField(
            model_name='voteevent',
            name='items',
        ),
        migrations.AddField(
            model_name='votingitem',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vote.VoteEvent', verbose_name='归属'),
        ),
    ]
