# Generated by Django 2.0.7 on 2018-08-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0002_auto_20180814_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingitem',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='Vote.VoteEvent', verbose_name='归属'),
        ),
    ]
