# Generated by Django 2.0.7 on 2018-08-14 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0003_auto_20180814_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingcounter',
            name='item',
        ),
        migrations.AddField(
            model_name='votingitem',
            name='counter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vote.VotingCounter'),
        ),
    ]
