# Generated by Django 2.0.7 on 2018-08-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0004_auto_20180814_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteevent',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
