# Generated by Django 2.0.7 on 2018-08-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0005_voteevent_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteevent',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
