# Generated by Django 2.0.7 on 2018-08-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0006_auto_20180815_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='counter',
        ),
        migrations.AddField(
            model_name='voter',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='Vote.VotingItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votingitem',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='VotingCounter',
        ),
    ]
