# Generated by Django 2.0.7 on 2018-08-16 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0007_auto_20180816_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteevent',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='是否开放'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 16, 30, 50, 904112), verbose_name='投票时间'),
        ),
    ]
