# Generated by Django 2.0.7 on 2018-08-16 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0008_auto_20180816_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='vote_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投票时间'),
        ),
    ]
