# Generated by Django 2.0.7 on 2018-08-20 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0009_auto_20180816_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='item',
        ),
        migrations.AddField(
            model_name='voter',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='Vote.VoteEvent'),
            preserve_default=False,
        ),
    ]
