# Generated by Django 2.0.7 on 2018-09-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0010_auto_20180820_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatOpenID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=64)),
                ('access_token', models.CharField(max_length=128)),
            ],
        ),
    ]
