# Generated by Django 2.0.7 on 2018-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0011_wechatopenid'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingitem',
            name='org',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='机构名称'),
        ),
    ]
