# Generated by Django 2.0.7 on 2018-09-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0012_votingitem_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
