# Generated by Django 2.0.7 on 2018-09-30 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0013_voter_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='vote_item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='Vote.VotingItem'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote_count',
            field=models.IntegerField(default=1),
        ),
    ]
